name: Blocklist compile

on:
  schedule:
    - cron: "0 5 * * *" # every day at 05:00 am
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm i -g @adguard/hostlist-compiler
      - run: hostlist-compiler -c conf.json -o output.txt
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Nightly update blocklist
          commit_user_name: Dungeon master
